### ISSUE TITLE
unable to parse html with DOCTYPE

### ISSUE THREAD

**Issue by RameshY703** [ershov-konst/dom-parser#12]
**TypeError: Cannot read property 'childNodes' of null**

**<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">**

when i remove this from start it works but get above error with it.

**Comment by sharunspi** [comment]
can you share the code .i have tested with HTML5 code , but I didn't get any error

**Comment by ershov-konst** [comment]
Thanks, @RameshY703 for highlighting that. The issue is fixed. I also added tests for that particular case https://github.com/ershov-konst/dom-parser/pull/30
