### ISSUE TITLE
Getting meaningless result

### ISSUE THREAD

**Issue by ajitqait** [ershov-konst/dom-parser#13]
var DomParser = require('dom-parser');
        var parser = new DomParser();

        fs.readFile("D:\\pageLoadPerformance\\pageLoad\\BI.html", 'utf8', function (err, html) {
            if (!err) {
                var document:Document = parser.parseFromString(html);
                console.log(document)
                 
                console.log(document.getElementsByTagName("a")[0].innerText)
            }
        })

Output : Node { namespace: null, text: undefined, _selfCloseTag: false }

**Comment by ershov-konst** [comment]
@ajitqait Hello! It all depends on the result you want to get. This library is designed to quickly find the necessary elements in HTML without first parsing the entire document (because of this, it works quickly).

For example we have html
```
let html = 
  `<!DOCTYPE html>
   <html lang="en">
     <head>
  	   <title>Title</title>
     </head>
     <body>
  	   <div class="root">
  	     <a href="https://github.com/ershov-konst/dom-parser/">dom-parser</a>
  	   </div>
     </body>
   </html>`;
```
Parse them
```
let document = parser.parseFromString(html);
```
This console.log output really meaningless result, and we don't need this.
```
console.log(document);
```
This console.log output `undefined`, because property `innerText` is not implemented. You may use `textContent` property, they returns expected result.       
```
console.log(document.getElementsByTagName("a")[0].innerText);
```
This console.log output "dom-parser" string
```
console.log(document.getElementsByTagName("a")[0].textContent);
```

**Comment by ajitqait** [comment]
I have tried textContent instead of innerText but still getting same result
-undefined

**Comment by ershov-konst** [comment]
Can you send an example of the page that you are trying to parse and the sample code that you want to do this?

**Comment by holysoles** [comment]
I was having the same issue but textContent worked for me. Thanks!

**Comment by JarlTetrazepam** [comment]
Bit of a necro here but I'm in the same spot as ajitqait two years ago. I'm trying to parse an XML file from an RSS feed and I need the content of the tags. I should note that I have never done this, so I expect the problem to be on my side somewhere.

This is an example of the RSS that I modified for readability. Idea should be the same though
`<rss version="2.0">
<channel>
<item>
    <title>Example RSS</title>
</item>
<item>
...
</item>
...
</channel
`
And this is what I have so far (Using node-fetch, should be irrelevant here though)
`
fetch(fURL)
        .then(response => response.text())
        .then(string => parser.parseFromString(string, "text/xml"))
        .then(data => {
            console.log(data.getElementsByTagName("title")[0].textContent) //outputs undefined
            })
`
It logs undefined, while I want it to log `Example RSS`

**Comment by ershov-konst** [comment]
Hi @JarlTetrazepam ! It looks like this issue is gone after migration to TS of the entire project. Anyway, I've added the test that addresses your case. Thank you.
