### ISSUE TITLE
getElementById('id').outerHTML is skipping empty spaces before closing tags

### ISSUE THREAD

**Issue by sudipstha08** [ershov-konst/dom-parser#19]

**Comment by sudipstha08** [comment]
`<div id="id123">Built with <a href="http://ajarproductions.com/pages/products/in5/?ref=footer" target="_blank" >In5</a>.</div>`

Theres a empty space at the end of opening a tag just after "_blank". But getElementById('id123').outerHTML returns the div without that space.

**Comment by ershov-konst** [comment]
Hi, @sudipstha08 ! Thank you for highlighting that. Indeed, this works like you mentioned, but it works similarly in a browser. In terms of the purpose of this library, this space only matters a little. Let me know If you have a particular case in which you experience a problem with the current implementation.
